config/routes.rb
Rails.application.routes.draw do

  resources :test_suites do
    resources :notification_rules
    resources :results
    resources :test_suite_runs
    resources :test_cases do
      resources :results
      resources :notification_rules
      resources :assertions 
    end
  end

  root 'test_suites#index'

end

app/models/test_suite_run.rb
class TestSuiteRun < ActiveRecord::Base
  has_many :results, dependent: :destroy
  has_many :login_results, dependent: :destroy
  belongs_to :test_suites

  def did_pass?
    login_result=self.login_results
    test_case_results=self.results

    #if (!login_result[0].pass)
    #  return false
    #end
  
    test_case_results.each do |result|
      if (!result.pass)
        return false
      end
    end
    return true
  end

  def save_and_check_notifications
    save!

    test_suite=TestSuite.find(self.test_suite_id)

    #If we are updating to set the completion of a test_suite, we should send notifications for any failures that happened
    failures=self.results.find_by(:pass=>false)

    #Find by is dumb and returns just the one result if there is only one. drop it into an array so we can resure the same code
    if (failures.is_a? Result)
      failures=[failures]
    end

    #No need to continue if no failures, otherwise get the count
    if (failures.nil?)
      return
    end

    #Create a summary of the failures
    summary=""
    failures.each do |failure|
      test_case=TestCase.find(failure.test_case_id)
      summary="#{summary}\nTest case #{test_case.id} failed with #{failure.response_code.to_s} - #{failure.reason.to_s}"
    end

    #Fire off each of the notification rules with their specific arguments
    test_suite.notification_rules.each do |rule|
      args=rule.args
      args=args.gsub '{TEST_SUITE_NAME}', "#{test_suite.name.to_s}"
      args=args.gsub '{SUMMARY}', "#{summary}"
      system "#{rule.script} #{args}"
    end
  end

end

app/controllers/test_suite_runs_controller.rb
class TestSuiteRunsController < ApplicationController
  before_action :set_test_suite_run, only: [:show, :edit, :update, :destroy]

  # GET /test_suite_runs
  # GET /test_suite_runs.json
  def index
    @test_suite = TestSuite.find(params[:test_suite_id])
    @test_suite_runs = @test_suite.test_suite_runs
  end

  # GET /test_suite_runs/1
  # GET /test_suite_runs/1.json
  def show
    @test_suite = TestSuite.find(params[:test_suite_id])
    @test_suite_runs = @test_suite.test_suite_runs.find(params[:id])
  end

  # GET /test_suite_runs/new
  def new
    @test_suite = TestSuite.find(params[:test_suite_id])
    @test_suite_run = TestSuiteRun.new
  end

  # GET /test_suite_runs/1/edit
  def edit
    @test_suite = TestSuite.find(params[:test_suite_id])
  end

  # POST /test_suite_runs
  # POST /test_suite_runs.json
  def create
    @test_suite = TestSuite.find(params[:test_suite_id])
    @test_suite_run = TestSuiteRun.new(test_suite_run_params)

    respond_to do |format|
      if @test_suite_run.save
        format.html { redirect_to test_suite_test_suite_runs(@test_suite_run,@test_suite_run), notice: 'Test suite run was successfully created.' }
        format.json { render :show, status: :created, location: @test_suite_run }
      else
        format.html { render :new }
        format.json { render json: @test_suite_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_suite_runs/1
  # PATCH/PUT /test_suite_runs/1.json
  def update
    @test_suite = TestSuite.find(params[:test_suite_id])

    respond_to do |format|
      if @test_suite_run.update(test_suite_run_params)
        format.html { redirect_to test_suite_test_suite_runs_path(@test_suite,@test_suite_run), notice: 'Test suite run was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_suite_run }
      else
        format.html { render :edit }
        format.json { render json: @test_suite_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_suite_runs/1
  # DELETE /test_suite_runs/1.json
  def destroy
    @test_suite = TestSuite.find(params[:test_suite_id])
    @test_suite_run.destroy
    respond_to do |format|
      format.html { redirect_to test_suite_test_suite_runs_url, notice: 'Test suite run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_suite_run
      @test_suite_run = TestSuiteRun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_suite_run_params
      params.require(:test_suite_run).permit(:start_time, :end_time, :test_suite_id)
    end
end

app/helpers/test_suite_runs_helper.rb
module TestSuiteRunsHelper
end

app/views/test_suite_runs/_form.html.erb
<%= form_for [@test_suite,@test_suite_run] do |f| %>
  <% if @test_suite_run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_suite_run.errors.count, "error") %> prohibited this test_suite_run from being saved:</h2>

      <ul>
      <% @test_suite_run.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :test_suite_id %><br>
    <%= f.number_field :test_suite_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_suite_runs/edit.html.erb
<h1>Editing test_suite_run</h1>

<%= render 'form' %>

<%= link_to 'Show', test_suite_test_suite_runs_path(@test_suite,@test_suite_run) %> |
<%= link_to 'Back', test_suite_test_suite_runs_path %>

app/views/test_suite_runs/index.html.erb
<h1>Listing test_suite_runs</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_suite_runs.each do |test_suite_run| %>
      <tr>
        <td><%= test_suite_run.start_time %></td>
        <td><%= test_suite_run.end_time %></td>
        <td><%= test_suite_run.did_pass? %></td>
        <td><%= link_to 'Show', test_suite_test_suite_run_path(@test_suite,test_suite_run) %></td>
        <td><%= link_to 'Destroy', test_suite_test_suite_run_path(@test_suite,test_suite_run), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test suite run', new_test_suite_test_suite_run_path %>

app/views/test_suite_runs/new.html.erb
<h1>New test_suite_run</h1>

<%= render 'form' %>

<%= link_to 'Back', test_suite_runs_path %>

app/views/test_suite_runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @test_suite_run.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @test_suite_run.end_time %>
</p>

<p>
  <strong>Test suite:</strong>
  <%= @test_suite_run.test_suite_id %>
</p>

<%= link_to 'Edit', edit_test_suite_test_suite_run_path(@test_suite,@test_suite_run) %> |
<%= link_to 'Back', test_suite_test_suite_runs_path(@test_suite,@test_suite_run) %>