config/routes.rb
Rails.application.routes.draw do

  resources :test_suites do
    resources :notification_rules
    resources :results
    resources :test_suite_runs
    resources :test_cases do
      resources :results
      resources :notification_rules
      resources :assertions 
    end
  end

  root 'test_suites#index'

end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :test_case
  belongs_to :test_suite
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @test_suite = TestSuite.find(params[:test_suite_id])
   
    if params[:test_case_id].present?
      @test_case = @test_suite.test_cases.find(params[:test_case_id])
      @results = @test_case.results.group_by{|r| TestCase.find(r.test_case_id) }
    else
      #All results are useless unless they are grouped by there test case
      @login_results=@test_suite.login_results.to_a
      @results = @test_suite.results.group_by{|r| TestCase.find(r.test_case_id) }
    end

  end

  # GET /results/1
  # GET /results/1.json
  def show
    @test_suite = TestSuite.find(params[:test_suite_id])
  end

  # GET /results/new
  def new
    @test_suite = TestSuite.find(params[:test_suite_id])
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
    @test_suite = TestSuite.find(params[:test_suite_id])
  end

  # POST /results
  # POST /results.json
  def create
    @test_suite = TestSuite.find(params[:test_suite_id])
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to test_suite_result_path(@test_suite,@result), notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    @test_suite = TestSuite.find(params[:test_suite_id])

    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to test_suite_result_path(@test_suite,@result), notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @test_suite = TestSuite.find(params[:test_suite_id])

    @result.destroy
    respond_to do |format|
      format.html { redirect_to test_suite_result_url(@test_suite), notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:response, :response_code, :datetime, :test_suite_run_id, :test_case_id)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for [@test_suite, @test_case, @result] do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :response %><br>
    <%= f.text_field :response %>
  </div>
  <div class="field">
    <%= f.label :response_code %><br>
    <%= f.number_field :response_code %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :test_suite_run_id %><br>
    <%= f.number_field :test_suite_run_id %>
  </div>
  <div class="field">
    <%= f.label :test_case_id %><br>
    <%= f.number_field :test_case_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', test_suite_result_path(@test_suite,@result) %> |
<%= link_to 'Back', test_suite_results_path(@test_suite,@result) %>

app/views/results/index.html.erb
<% response_time_data=@results.map{|tc| Hash["name",tc[0].name,"data",Hash[tc[1].map{|res| [res.datetime,res.response_time.nil? ? 0 : res.response_time]}]]} %>
<% pass_fail_data=@results.map{|tc| Hash["name",tc[0].name,"data",Hash[tc[1].map{|res| [res.datetime,res.pass ? 1 : 0 ]}]]} %>

<% if @test_case.nil? %>
  <h1><%= link_to @test_suite.name, @test_suite %> : Results</h1>
<% else %>
  <h1><%= link_to @test_suite.name, test_suite_results_path(@test_suite) %> : <%= link_to @test_case.name, test_suite_test_case_path(@test_suite,@test_case) %> : Results</h1>
<% end %>
  

<h2>Response Time</h2>
<%= line_chart response_time_data %>
<h2>Pass/Fail</h2>
<%= line_chart pass_fail_data %>
    <% @results.each do |test_case| %>
      <h2>Results for test case: <%=link_to test_case[0].name, test_suite_test_case_results_path(@test_suite,test_case[0]) %></h2>
      <table>
        <thead>
          <tr>
            <th>Datetime</th>
            <th>Response code</th>
            <th>Pass?</th>
            <th>Reason</th>
          </tr>
        </thead>
        <tbody>
      <% test_case[1].each do |result| %>
        <tr>
          <td><%= result.datetime %></td>
          <td><%= result.response_code %></td>
          <td><%= result.pass %></td>
          <td><%= result.reason %></td>
        </tr>
      <%end%>
      </tbody>
      </table>
    <% end %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Response:</strong>
  <%= @result.response %>
</p>

<p>
  <strong>Response code:</strong>
  <%= @result.response_code %>
</p>

<p>
  <strong>Pass?</strong>
  <%= @result.pass %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @result.reason %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @result.datetime %>
</p>

<p>
  <strong>Test suite run:</strong>
  <%= @result.test_suite_run_id %>
</p>

<p>
  <strong>Test case:</strong>
  <%= @result.test_case_id %>
</p>

<%= link_to 'Edit', edit_test_suite_result_path(@test_suite,@result) %> |
<%= link_to 'Back', test_suite_results_path %>