config/routes.rb
Rails.application.routes.draw do

  resources :test_suites do
    resources :notification_rules
    resources :results
    resources :test_suite_runs
    resources :test_cases do
      resources :results
      resources :notification_rules
      resources :assertions 
    end
  end

  root 'test_suites#index'

end

app/models/notification_rule.rb
class NotificationRule < ActiveRecord::Base
end

app/controllers/notification_rules_controller.rb
class NotificationRulesController < ApplicationController
  before_action :set_notification_rule, only: [:show, :edit, :update, :destroy]

  # GET /notification_rules
  # GET /notification_rules.json
  def index
    @test_suite=TestSuite.find(params[:test_suite_id])
    @notification_rules = @test_suite.notification_rules
  end

  # GET /notification_rules/1
  # GET /notification_rules/1.json
  def show
    @test_suite=TestSuite.find(params[:test_suite_id])
    @notification_rule = @test_suite.notification_rules.find(params[:id])
  end

  # GET /notification_rules/new
  def new
    @test_suite=TestSuite.find(params[:test_suite_id])
    @notification_rule = NotificationRule.new
  end

  # GET /notification_rules/1/edit
  def edit
    @test_suite=TestSuite.find(params[:test_suite_id])
  end

  # POST /notification_rules
  # POST /notification_rules.json
  def create
    @test_suite=TestSuite.find(params[:test_suite_id])
    @notification_rule = NotificationRule.new(notification_rule_params)

    respond_to do |format|
      if @notification_rule.save
        format.html { redirect_to test_suite_notification_rule_path(@test_suite,@notification_rule), notice: 'Notification rule was successfully created.' }
        format.json { render :show, status: :created, location: @notification_rule }
      else
        format.html { render :new }
        format.json { render json: @notification_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notification_rules/1
  # PATCH/PUT /notification_rules/1.json
  def update
    @test_suite=TestSuite.find(params[:test_suite_id])
    respond_to do |format|
      if @notification_rule.update(notification_rule_params)
        format.html { redirect_to test_suite_notification_rule_path(@test_suite,@notification_rule), notice: 'Notification rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification_rule }
      else
        format.html { render :edit }
        format.json { render json: @notification_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification_rules/1
  # DELETE /notification_rules/1.json
  def destroy
    @test_suite=TestSuite.find(params[:test_suite_id])
    @notification_rule.destroy
    respond_to do |format|
      format.html { redirect_to notification_rules_url, notice: 'Notification rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification_rule
      @notification_rule = NotificationRule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_rule_params
      params.require(:notification_rule).permit(:name, :script, :args, :test_case_id, :test_suite_id)
    end
end

app/helpers/notification_rules_helper.rb
module NotificationRulesHelper
end

app/views/notification_rules/_form.html.erb
<%= form_for [@test_suite,@notification_rule] do |f| %>
  <% if @notification_rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification_rule.errors.count, "error") %> prohibited this notification_rule from being saved:</h2>

      <ul>
      <% @notification_rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :script %><br>
    <%= f.text_field :script %>
  </div>
  <div class="field">
    <%= f.label :args %><br>
    <%= f.text_field :args %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notification_rules/edit.html.erb
<h1>Editing notification_rule</h1>

<%= render 'form' %>

<%= link_to 'Show', test_suite_notification_rule_path(@test_suite,@notification_rule) %> |
<%= link_to 'Back', test_suite_notification_rules_path %>

app/views/notification_rules/index.html.erb
<h1><%= link_to @test_suite.name, @test_suite %> : Notification Rules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Script</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @notification_rules.each do |notification_rule| %>
      <tr>
        <td><%= notification_rule.name %></td>
        <td><%= notification_rule.script %></td>
        <td><%= link_to 'Show', test_suite_notification_rule_path(@test_suite,notification_rule) %></td>
        <td><%= link_to 'Edit', edit_test_suite_notification_rule_path(@test_suite,notification_rule) %></td>
        <td><%= link_to 'Destroy', test_suite_notification_rule_path(@test_suite,notification_rule), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification rule', new_test_suite_notification_rule_path(@test_suite) %>

app/views/notification_rules/new.html.erb
<h1>New notification_rule</h1>

<%= render 'form' %>

<%= link_to 'Back', test_suite_notification_rules_path(@test_suite) %>

app/views/notification_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @notification_rule.name %>
</p>

<p>
  <strong>Script:</strong>
  <%= @notification_rule.script %>
</p>

<p>
  <strong>Args:</strong>
  <%= @notification_rule.args %>
</p>

<%= link_to 'Edit', edit_test_suite_notification_rule_path(@test_suite,@notification_rule) %> |
<%= link_to 'Back', test_suite_notification_rules_path(@test_suite,@notification_rule) %>