config/routes.rb
Rails.application.routes.draw do

  resources :test_suites do
    resources :notification_rules
    resources :results
    resources :test_suite_runs
    resources :test_cases do
      resources :results
      resources :notification_rules
      resources :assertions 
    end
  end

  root 'test_suites#index'

end

app/models/test_suite.rb
class TestSuite < ActiveRecord::Base
  has_many :test_cases, dependent: :destroy
  has_many :notification_rules, dependent: :destroy
  has_many :test_suite_runs, dependent: :destroy
  has_many :results, through: :test_suite_runs
  has_many :login_results, through: :test_suite_runs

  def last_run
    TestSuiteRun.order(:start_time=>:desc).limit(1).find_by(:test_suite_id=>self.id)
  end
end

app/controllers/test_suites_controller.rb
class TestSuitesController < ApplicationController
  before_action :set_test_suite, only: [:show, :edit, :update, :destroy]

  # GET /test_suites
  # GET /test_suites.json
  def index
    @test_suites = TestSuite.all
  end

  # GET /test_suites/1
  # GET /test_suites/1.json
  def show
  end

  # GET /test_suites/new
  def new
    @test_suite = TestSuite.new
  end

  # GET /test_suites/1/edit
  def edit
  end

  # POST /test_suites
  # POST /test_suites.json
  def create
    @test_suite = TestSuite.new(test_suite_params)

    respond_to do |format|
      if @test_suite.save
        format.html { redirect_to @test_suite, notice: 'Test suite was successfully created.' }
        format.json { render :show, status: :created, location: @test_suite }
      else
        format.html { render :new }
        format.json { render json: @test_suite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_suites/1
  # PATCH/PUT /test_suites/1.json
  def update
    respond_to do |format|
      if @test_suite.update(test_suite_params)
        format.html { redirect_to @test_suite, notice: 'Test suite was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_suite }
      else
        format.html { render :edit }
        format.json { render json: @test_suite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_suites/1
  # DELETE /test_suites/1.json
  def destroy
    @test_suite.destroy
    respond_to do |format|
      format.html { redirect_to test_suites_url, notice: 'Test suite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_suite
      @test_suite = TestSuite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_suite_params
      params.require(:test_suite).permit(:base_url, :oauth_url, :client_id, :username, :password, :interval, :name)
    end
end

app/helpers/test_suites_helper.rb
module TestSuitesHelper
end

app/views/test_suites/_form.html.erb
<%= form_for(@test_suite) do |f| %>
  <% if @test_suite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_suite.errors.count, "error") %> prohibited this test_suite from being saved:</h2>

      <ul>
      <% @test_suite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :base_url %><br>
    <%= f.text_field :base_url %>
  </div>
  <div class="field">
    <%= f.label :oauth_url %><br>
    <%= f.text_field :oauth_url %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :interval %><br>
    <%= f.number_field :interval %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_suites/edit.html.erb
<h1>Editing test_suite</h1>

<%= render 'form' %>

<%= link_to 'Test Cases', test_suite_test_cases_path(@test_suite) %> |
<%= link_to 'Notification Rules', test_suite_notification_rules_path(@test_suite) %> |
<%= link_to 'Back', test_suites_path %>

app/views/test_suites/index.html.erb
<h1>All Test Suites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Interval</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @test_suites.each do |test_suite| %>
      <tr>
        <td><%= test_suite.name %></td>
        <td><%= test_suite.username %></td>
        <td><%= test_suite.interval %></td>
        <td><%= link_to 'Edit', edit_test_suite_path(test_suite) %></td>
        <td><%= link_to 'Results', test_suite_results_path(test_suite) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test suite', new_test_suite_path %>

app/views/test_suites/new.html.erb
<h1>New test_suite</h1>

<%= render 'form' %>

<%= link_to 'Back', test_suites_path %>

app/views/test_suites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oauth url:</strong>
  <%= @test_suite.oauth_url %>
</p>

<p>
  <strong>Client:</strong>
  <%= @test_suite.client_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @test_suite.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @test_suite.password %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @test_suite.interval %>
</p>

<p>
  <strong>Name:</strong>
  <%= @test_suite.name %>
</p>

<%= link_to 'Edit', edit_test_suite_path(@test_suite) %> |
<%= link_to 'Test Cases', test_suite_test_cases_path(@test_suite) %> |
<%= link_to 'Notification Rules', test_suite_notification_rules_path(@test_suite) %> |
<%= link_to 'Back', test_suites_path %>